import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "EU Job Search Guides — EuroCareer AI",
    description:
        "Free guides on writing CVs, finding jobs, and navigating the European job market. Practical advice for every EU country.",
        };

        const GUIDES = [
          {
              tag: "CV Guide",
                  flag: "\u{1F1E9}\u{1F1EA}",
                      title: "How to write a CV for Germany in 2026",
                          desc: "German CVs follow strict conventions around format, photo, and structure.",
                              href: "/blog/german-cv-format",
                                },
                                  {
                                      tag: "Job Search",
                                          flag: "\u{1F1F3}\u{1F1F1}",
                                              title: "Finding jobs in the Netherlands as a foreigner",
                                                  desc: "The Dutch job market is open to internationals — here is how to stand out.",
                                                      href: "/blog/netherlands-job-search",
                                                        },
                                                          {
                                                              tag: "CV Guide",
                                                                  flag: "\u{1F1EA}\u{1F1FA}",
                                                                      title: "EU vs US resume: key differences explained",
                                                                          desc: "Here is exactly what to change before you hit send on an EU application.",
                                                                              href: "/blog/eu-vs-us-resume",
                                                                                },
                                                                                ];

                                                                                export default function BlogIndexPage() {
                                                                                  return (
                                                                                      <div className="min-h-screen bg-white">
                                                                                            {/* NAV */}
                                                                                                  <nav className="border-b border-[#E2E1DC] bg-white/90 backdrop-blur-sm sticky top-0 z-50">
                                                                                                          <div className="max-w-5xl mx-auto px-6 py-3.5 flex items-center justify-between">
                                                                                                                    <Link href="/" className="flex items-center gap-2">
                                                                                                                                <Image src="/LOGO_NEW.png" alt="EuroCareer AI" width={140} height={32} className="h-8 w-auto" />
                                                                                                                                          </Link>
                                                                                                                                                    <div className="flex items-center gap-3">
                                                                                                                                                                <Link href="/auth/login" className="text-sm text-[#3D4255] hover:text-[#0F1629] transition-colors font-medium">Sign in</Link>
                                                                                                                                                                            <Link href="/auth/signup" className="text-sm font-semibold px-4 py-2 rounded-lg text-white transition-all hover:-translate-y-0.5 hover:shadow-md" style={{ background: "#636DF5" }}>Start free</Link>
                                                                                                                                                                                      </div>
                                                                                                                                                                                              </div>
                                                                                                                                                                                                    </nav>
                                                                                                                                                                                                    
                                                                                                                                                                                                          <main className="max-w-5xl mx-auto px-6 py-16">
                                                                                                                                                                                                                  <div className="mb-12">
                                                                                                                                                                                                                            <div className="inline-flex items-center gap-2 text-xs font-semibold text-[#636DF5] uppercase tracking-widest mb-3">
                                                                                                                                                                                                                                        <Image src="/STAR.png" alt="" width={14} height={14} className="opacity-60" />
                                                                                                                                                                                                                                                    Guides
                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                        <h1 className="text-4xl sm:text-5xl font-extrabold text-[#0F1629] mb-4" style={{ fontFamily: "'Outfit', sans-serif" }}>
                                                                                                                                                                                                                                                                                    EU job search guides
                                                                                                                                                                                                                                                                                              </h1>
                                                                                                                                                                                                                                                                                                        <p className="text-lg text-[#7A7F94] max-w-2xl">
                                                                                                                                                                                                                                                                                                                    Practical advice on CVs, cover letters, and job searching across European markets. Written for international professionals.
                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                              <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
                                                                                                                                                                                                                                                                                                                                                        {GUIDES.map((post) => (
                                                                                                                                                                                                                                                                                                                                                                    <Link
                                                                                                                                                                                                                                                                                                                                                                                  key={post.title}
                                                                                                                                                                                                                                                                                                                                                                                                href={post.href}
                                                                                                                                                                                                                                                                                                                                                                                                              className="group rounded-2xl border border-[#E2E1DC] bg-[#F8F8F6] p-6 hover:border-[#636DF5] hover:shadow-md transition-all hover:-translate-y-0.5 flex flex-col gap-3"
                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-2xl">{post.flag}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-xs font-semibold text-[#636DF5] uppercase">{post.tag}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="font-bold text-[#0F1629] leading-snug text-sm" style={{ fontFamily: "'Outfit', sans-serif" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {post.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-xs text-[#7A7F94] flex-1">{post.desc}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-sm font-medium text-[#636DF5] group-hover:underline">Read guide →</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Footer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <footer className="border-t border-[#E2E1DC] py-10 mt-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="max-w-5xl mx-auto px-6 flex flex-col sm:flex-row items-center justify-between gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex items-center gap-2 text-sm text-[#7A7F94]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Image src="/STAR.png" alt="" width={18} height={18} className="opacity-50" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>© {new Date().getFullYear()} EuroCareer AI</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-6 text-sm text-[#B0B4C5]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link href="/privacy" className="hover:text-[#3D4255] transition-colors">Privacy</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link href="/terms" className="hover:text-[#3D4255] transition-colors">Terms</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
